/**
 * @module investorContext
 * Loads and provides the pre-generated investor briefing (Константин Денисенко)
 * for injection into the voice assistant's system prompt.
 *
 * The briefing is generated by scripts/summarize_investor.py and stored
 * in data/investor_kostya_context.md. It is loaded once at startup and
 * cached in memory.
 *
 * This context is injected into the CRITICAL slot of the context manager
 * so it is NEVER evicted from the context window.
 */

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { logger } from "@/lib/logger";

// ── Types ────────────────────────────────────────────────────

export interface InvestorContext {
    /** The full briefing text (markdown) */
    briefing: string;
    /** Character count */
    chars: number;
    /** Whether the briefing was loaded successfully */
    loaded: boolean;
    /** Source file path */
    sourcePath: string;
    /** Generation timestamp from frontmatter */
    generated?: string;
}

// ── Cache ────────────────────────────────────────────────────

let _cached: InvestorContext | null = null;

// ── Loader ───────────────────────────────────────────────────

/**
 * Strip YAML frontmatter from markdown content.
 */
function stripFrontmatter(content: string): { body: string; meta: Record<string, string> } {
    const match = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)/);
    if (!match) return { body: content, meta: {} };

    const meta: Record<string, string> = {};
    for (const line of match[1].split("\n")) {
        const kv = line.match(/^(\w+):\s*(.+)/);
        if (kv) meta[kv[1]] = kv[2].trim();
    }
    return { body: match[2], meta };
}

/**
 * Load the investor context briefing from disk.
 * Returns cached version if already loaded.
 */
export function loadInvestorContext(): InvestorContext {
    if (_cached) return _cached;

    const filePath = join(process.cwd(), "data", "investor_kostya_context.md");

    if (!existsSync(filePath)) {
        logger.warn(`[InvestorContext] Briefing file not found: ${filePath}`);
        _cached = {
            briefing: "",
            chars: 0,
            loaded: false,
            sourcePath: filePath,
        };
        return _cached;
    }

    try {
        const raw = readFileSync(filePath, "utf-8");
        const { body, meta } = stripFrontmatter(raw);

        // Validate: must have meaningful content
        if (body.trim().length < 100) {
            logger.warn("[InvestorContext] Briefing too short, skipping");
            _cached = {
                briefing: "",
                chars: 0,
                loaded: false,
                sourcePath: filePath,
                generated: meta.generated,
            };
            return _cached;
        }

        _cached = {
            briefing: body.trim(),
            chars: body.trim().length,
            loaded: true,
            sourcePath: filePath,
            generated: meta.generated,
        };

        logger.info(
            `[InvestorContext] Loaded investor briefing: ${_cached.chars} chars, generated: ${meta.generated ?? "unknown"}`,
        );
        return _cached;
    } catch (err) {
        logger.error(`[InvestorContext] Failed to load briefing: ${err}`);
        _cached = {
            briefing: "",
            chars: 0,
            loaded: false,
            sourcePath: filePath,
        };
        return _cached;
    }
}

/**
 * Build the investor context block for injection into the system prompt.
 * Returns empty string if no briefing is available.
 */
export function buildInvestorContextBlock(): string {
    const ctx = loadInvestorContext();
    if (!ctx.loaded || !ctx.briefing) return "";

    return `

═══════════════════════════════════════════════
ПОЛНАЯ ИНФОРМАЦИЯ О ИНВЕСТОРЕ — КОНСТАНТИН ДЕНИСЕНКО (КОСТЯ)
Ты ОБЯЗАНА знать ВСЮ эту информацию. Когда Антон спрашивает про Костю,
деньги, инвестиции, Lixiang, Dominion — отвечай ДЕТАЛЬНО из этого брифинга.
═══════════════════════════════════════════════

${ctx.briefing}

═══════════════════════════════════════════════
КОНЕЦ БРИФИНГА ПО ИНВЕСТОРУ
═══════════════════════════════════════════════
`;
}

/**
 * Get the character count of the investor context block.
 * Used for context budget calculations.
 */
export function getInvestorContextChars(): number {
    const block = buildInvestorContextBlock();
    return block.length;
}

/**
 * Force reload the investor context from disk.
 * Call this after regenerating the briefing via summarize_investor.py.
 */
export function reloadInvestorContext(): InvestorContext {
    _cached = null;
    return loadInvestorContext();
}
